<a href="https://colab.research.google.com/github/gurram-rohith/MDS-LAB/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
print(sys.version)

3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]


## Comparing NumPy Arrays and Python Lists: Time and Space Efficiency

This section will demonstrate the performance differences between NumPy arrays and standard Python lists, focusing on execution time for numerical operations and memory consumption.

In [ ]:
import time
import sys
import numpy as np

# Define the size of the arrays/lists for demonstration
SIZE = 1000000

### 1. Time Efficiency: Element-wise Addition

In [ ]:
# Create Python lists
# The built-in 'list' function was shadowed by a variable 'list' in the global scope.
# We use __builtins__.list to explicitly refer to the original list constructor.
list1 = __builtins__.list(range(10))
list2 = __builtins__.list(range(10))

# Measure time for Python list addition
start_time = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for list addition: {list_time:.6f} seconds")

# Create NumPy arrays
numpy_array1 = np.arange(10)
numpy_array2 = np.arange(10)

# Measure time for NumPy array addition
start_time = time.time()
result_numpy = numpy_array1 + numpy_array2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for NumPy array addition: {numpy_time:.6f} seconds")

print(f"\nNumPy array addition is approximately {list_time / numpy_time:.2f} times faster than list addition.")

Time taken for list addition: 0.000118 seconds
Time taken for NumPy array addition: 0.000136 seconds

NumPy array addition is approximately 0.87 times faster than list addition.


### 2. Space Efficiency: Memory Consumption

In [ ]:
# Measure memory for Python list
list_memory = sys.getsizeof(list1) + sum(sys.getsizeof(item) for item in list1[:1000]) * (SIZE / 1000) # Estimate for elements
print(f"Memory occupied by Python list: {list_memory / (1024 * 1024):.2f} MB")

# Measure memory for NumPy array
numpy_memory = numpy_array1.nbytes
print(f"Memory occupied by NumPy array: {numpy_memory / (1024 * 1024):.2f} MB")

print(f"\nNumPy array uses approximately {list_memory / numpy_memory:.2f} times less memory than a Python list (estimated). This estimation for Python lists can vary due to object overhead for each element.")

Memory occupied by Python list: 0.27 MB
Memory occupied by NumPy array: 0.00 MB

NumPy array uses approximately 3501.70 times less memory than a Python list (estimated). This estimation for Python lists can vary due to object overhead for each element.


In [ ]:
list1=[73,2,3]
print(type(list1))
arr1=np.array(list1)
print(type(arr1))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
arr1.ndim


1

In [ ]:
print(arr1.size)

3


In [ ]:
arr1.shape

(3,)

In [ ]:
tuple1=(1,23,45)
type(tuple1)

tuple

In [ ]:

arr1.nbytes


24

In [ ]:
l1=[[73,2],[5,6]]
a=np.array(l1)
a

array([[73,  2],
       [ 5,  6]])

In [ ]:
l1

[[73, 2], [5, 6]]

In [ ]:
type(l1)

list

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 2)

In [ ]:
a.size

4

In [ ]:
a1=np.array([73,2,3,4,5,6,7,8,9,10])
print(a1)

[73  2  3  4  5  6  7  8  9 10]


In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a1.ndim

1

In [ ]:
a1.size

10

In [ ]:
a2=np.arange(0,1000)
a2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
a2=np.arange(0,20)
a2[0]=73

In [ ]:
a2

array([73,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a2[1]=10
a2

array([73, 10, 18])

In [ ]:
a2.max()

np.int64(73)

In [ ]:
a2.dtype

dtype('int64')

In [ ]:
a3=np.array([73,2,3,4],dtype="float")
a3

array([73.,  2.,  3.,  4.])

In [ ]:
a3.dtype.name

'float64'

In [ ]:
a3.astype("int")

array([73,  2,  3,  4])

In [ ]:
a4=a3
a4.dtype.name

'float64'

In [ ]:
a=np.array([[73,2],[3,4]])

In [ ]:
a

array([[73,  2],
       [ 3,  4]])

In [ ]:
a.ndim

2

In [ ]:
a.size

4

In [ ]:
a.size

4

In [ ]:
a.shape

(2, 2)

In [ ]:
a.nbytes

32

In [ ]:
# Create a 1D array using arange
arr_1d = np.arange(12)
arr_1d[0]=73
print("1D Array:\n", arr_1d)

# Reshape the 1D array into a 2D array (e.g., 3 rows, 4 columns)
arr_2d = arr_1d.reshape(3, 4)
print("\n2D Array:\n", arr_2d)
print("Shape of 2D Array:", arr_2d.shape)

1D Array:
 [73  1  2  3  4  5  6  7  8  9 10 11]

2D Array:
 [[73  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape of 2D Array: (3, 4)


In [ ]:
mat2=np.arange(0,10)
mat2[0]=73
mat3=mat2.reshape(2,5)
mat3

array([[73,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [ ]:
mat4=np.zeros((4,4))
mat4[0,0]=73
mat4

array([[73.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [ ]:
mat4.astype("int")

array([[73,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [ ]:
mat4=np.ones((4,4))
mat4[0,0]=73
mat4

array([[73.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [ ]:
mat4=np.full((4,4),2)
mat4[0,0]=73
mat4

array([[73,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2]])

In [ ]:
mat4[1][1]=4

In [ ]:
mat4

array([[73,  2,  2,  2],
       [ 2,  4,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2]])

In [ ]:
mat4=np.eye(5,dtype="int")
mat4[0,0]=73

In [ ]:
mat4

array([[73,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  1]])

In [ ]:
a5=np.random.randint(10)

In [ ]:
a5

1

In [ ]:
mat1=np.linspace(0,2,5)
mat1[0]=73

In [ ]:
mat1

array([73. ,  0.5,  1. ,  1.5,  2. ])

In [ ]:
mat = np.array([[73, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
print(f"Modified mat: {mat}")

Modified mat: [[73  1  2  3  4]
 [ 5  6  7  8  9]]


In [ ]:
mat.flatten()
mat

array([[73,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

## Converting Strings to Arrays

In [ ]:
string_data = "73hello"
array_from_string = np.array(__builtins__.list(string_data))
print(f"String: {string_data}")
print(f"Array from string: {array_from_string}")
print(f"Type of array from string: {type(array_from_string)}")

String: 73hello
Array from string: ['7' '3' 'h' 'e' 'l' 'l' 'o']
Type of array from string: <class 'numpy.ndarray'>


## Converting Arrays to Sets

In [ ]:
array_to_convert = np.array([73, 2, 2, 3, 4, 4, 5])
set_from_array = set(array_to_convert)
print(f"NumPy Array: {array_to_convert}")
print(f"Set from array: {set_from_array}")
print(f"Type of set from array: {type(set_from_array)}")

NumPy Array: [73  2  2  3  4  4  5]
Set from array: {np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(73)}
Type of set from array: <class 'set'>


In [ ]:
mat3d=np.array([[[73,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(mat3d)

[[[73  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
mat3d[0][0][0]=73
mat3d

array([[[73,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Operations on a 3D Matrix (NumPy Array)

In [ ]:
# Assuming mat3d is already defined as:
# mat3d=np.array([[[73,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# print(mat3d)

print("Original 3D Matrix (mat3d):\n", mat3d)

Original 3D Matrix (mat3d):
 [[[73  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### 1. Shape and Dimensions

In [ ]:
print( {mat3d.shape})
print({mat3d.ndim})
print( {mat3d.size})

{(2, 2, 3)}
{3}
{12}


#### 2. Indexing and Slicing

In [ ]:
# Accessing a specific element (e.g., first depth, first row, first column)
print(f"Element at (0, 0, 0): {mat3d[0, 0, 0]}")

# Accessing an entire 2D slice (e.g., the first matrix/depth)
print(f"\nFirst 2D slice:\n{mat3d[0]}")

# Accessing a specific row across all depths (e.g., first row of all matrices)
print(f"\nFirst row across all depths:\n{mat3d[:, 0, :]}")

# Slicing a sub-matrix
print(f"\nSub-matrix from first depth, first row to second column:\n{mat3d[0, :, :2]}")

Element at (0, 0, 0): 73

First 2D slice:
[[73  2  3]
 [ 4  5  6]]

First row across all depths:
[[73  2  3]
 [ 7  8  9]]

Sub-matrix from first depth, first row to second column:
[[73  2]
 [ 4  5]]


#### 3. Mathematical Operations

In [ ]:
# Element-wise addition (e.g., adding 10 to every element)
added_matrix = mat3d + 10
print(f"Matrix after adding 10:\n{added_matrix}")

# Element-wise multiplication
multiplied_matrix = mat3d * 2
print(f"\nMatrix after multiplying by 2:\n{multiplied_matrix}")

# Sum of all elements
print(f"\nSum of all elements: {mat3d.sum()}")

# Sum along a specific axis (e.g., sum along depth, axis=0)
print(f"\nSum along axis 0 (depth):\n{mat3d.sum(axis=0)}")

# Mean of all elements
print(f"\nMean of all elements: {mat3d.mean():.2f}")

Matrix after adding 10:
[[[83 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]]

Matrix after multiplying by 2:
[[[146   4   6]
  [  8  10  12]]

 [[ 14  16  18]
  [ 20  22  24]]]

Sum of all elements: 150

Sum along axis 0 (depth):
[[80 10 12]
 [14 16 18]]

Mean of all elements: 12.50


#### 4. Reshaping

In [ ]:
# Reshaping to a 1D array
reshaped_1d = mat3d.reshape(-1)
print(f"Reshaped to 1D:\n{reshaped_1d}")

# Reshaping to a different 2D or 3D shape (if compatible with total elements)
# Original shape: (2, 2, 3), total elements: 12
# Reshape to (3, 4) - 3 rows, 4 columns
reshaped_2d = mat3d.reshape(3, 4)
print(f"\nReshaped to 2D (3x4):\n{reshaped_2d}")

Reshaped to 1D:
[73  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 2D (3x4):
[[73  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### 5. Transposing

In [ ]:
# Transposing the axes (default swaps first and last axis)
transposed_matrix = mat3d.transpose()
print(f"Transposed matrix (default):\n{transposed_matrix}")
print(f"Shape of transposed matrix: {transposed_matrix.shape}")

# Permuting axes explicitly (e.g., swap depth and rows, keep columns)
# Original axes: 0 (depth), 1 (rows), 2 (columns)
# New order: 1 (rows), 0 (depth), 2 (columns)
permuted_matrix = mat3d.transpose((1, 0, 2))
print(f"\nMatrix with axes permuted (rows, depth, columns):\n{permuted_matrix}")
print(f"Shape of permuted matrix: {permuted_matrix.shape}")

Transposed matrix (default):
[[[73  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]
Shape of transposed matrix: (3, 2, 2)

Matrix with axes permuted (rows, depth, columns):
[[[73  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
Shape of permuted matrix: (2, 2, 3)


In [ ]:
import numpy as np
a1=np.array((73,2,3,4,5))

In [ ]:
np.random.choice(a1)

np.int64(3)

In [ ]:
np.random.shuffle(a1)

In [ ]:
a1

array([ 5,  2,  3,  4, 73])

In [ ]:
a1[:2]

array([5, 2])

In [ ]:
a1[::-2]

array([73,  3,  5])

In [ ]:
a1[::2]

array([ 5,  3, 73])

In [ ]:
mat2=np.array([[73,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [ ]:
print(mat2[1,2])

6


In [ ]:
print(mat2[:2])

[[73  2  3]
 [ 4  5  6]]


In [ ]:
print(mat2[1:2])

[[4 5 6]]


In [ ]:
print(f"Original matrix:{mat2}")
print(f"Last two elements of the  row: {mat2[0::, -2:]}")

Original matrix:[[73  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Last two elements of the  row: [[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


In [ ]:
mat2[0,0]

np.int64(73)

In [ ]:
mat2[1::1,1::-1]

array([[ 5,  4],
       [ 8,  7],
       [11, 10]])

In [ ]:
arr1=np.array([73,4,5,6])
arr2=np.array([73,0,1,2])
a3=np.concatenate((arr1,arr2))
a3

array([73,  4,  5,  6, 73,  0,  1,  2])

In [ ]:
a3=arr1+arr2

In [ ]:
a3

array([146,   4,   6,   8])

In [ ]:
arr4=np.array([73,4,3,5,6])
np.random.seed(3)
np.random.shuffle(arr4)

In [ ]:
arr4

array([ 5,  6,  4, 73,  3])

In [ ]:
mat2.reshape(3,4)

array([[73,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a3=np.stack((arr1,arr2))

In [ ]:
a3

array([[73,  4,  5,  6],
       [73,  0,  1,  2]])

In [ ]:

print(f"Original matrix:\n{mat2}")

# Condition 1: Select all elements greater than 5
condition_gt_5 = mat2 > 5
print(f"\nBoolean mask for elements > 5:\n{condition_gt_5}")
print(f"Elements greater than 5: {mat2[condition_gt_5]}")

Original matrix:
[[73  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Boolean mask for elements > 5:
[[ True False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]
Elements greater than 5: [73  6  7  8  9 10 11 12]


In [ ]:

print(f"Original matrix:\n{mat2}\n")
split_rows = np.split(mat2, 2, axis=0)
print(f"Splitting 'mat2' into 2 equal parts along rows (axis=0):\n{split_rows[0]}\n\n{split_rows[1]}\n")

Original matrix:
[[73  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Splitting 'mat2' into 2 equal parts along rows (axis=0):
[[73  2  3]
 [ 4  5  6]]

[[ 7  8  9]
 [10 11 12]]



In [ ]:

split_cols = np.split(mat2, 3, axis=1)
print(f"Splitting 'mat2' into 3 equal parts along columns (axis=1):\n{split_cols[0]}\n\n{split_cols[1]}\n\n{split_cols[2]}\n")

Splitting 'mat2' into 3 equal parts along columns (axis=1):
[[73]
 [ 4]
 [ 7]
 [10]]

[[ 2]
 [ 5]
 [ 8]
 [11]]

[[ 3]
 [ 6]
 [ 9]
 [12]]



In [ ]:

vsplit_result = np.vsplit(mat2, 2)
print(f"Vertical split of 'mat2' into 2 parts (np.vsplit):\n{vsplit_result[0]}\n\n{vsplit_result[1]}\n")

Vertical split of 'mat2' into 2 parts (np.vsplit):
[[73  2  3]
 [ 4  5  6]]

[[ 7  8  9]
 [10 11 12]]



In [ ]:

hsplit_result = np.hsplit(mat2, 3)
print(f"Horizontal split of 'mat2' into 3 parts (np.hsplit):\n{hsplit_result[0]}\n\n{hsplit_result[1]}\n\n{hsplit_result[2]}\n")

Horizontal split of 'mat2' into 3 parts (np.hsplit):
[[73]
 [ 4]
 [ 7]
 [10]]

[[ 2]
 [ 5]
 [ 8]
 [11]]

[[ 3]
 [ 6]
 [ 9]
 [12]]



In [ ]:
a1=np.array([73,2,3,4,5])
a1[::-2]


array([ 5,  3, 73])